# Configurations for google reviews

# List of all the branches that we want to study
list_of_links = {
'ENBD - Abu Dhabi - Abu Dhabi Main Office branch' : 'https://maps.app.goo.gl/e8LRD3JenGskh8Gd7',
'ENBD - Abu Dhabi - Electra Street Branch' : 'https://maps.app.goo.gl/7DkeJZcgaSbcK5ev7',
'ENBD - Abu Dhabi - Tourist Club Branch' : 'https://maps.app.goo.gl/bGziw18wxogPt2kbA',
'ENBD - Abu Dhabi - Al Ain Khalifa street Branch' : 'https://maps.app.goo.gl/VdBcEnq6fEKvAgpY8',
'ENBD - Abu Dhabi - Dalma Mall Branch' : 'https://maps.app.goo.gl/VKsjzRqAdcQXWeNr9',
'ENBD - Abu Dhabi - Khalifa Branch' : 'https://maps.app.goo.gl/Hbt5xb5DNGSqXRVC6',
'ENBD - Abu Dhabi - Khalidiya Branch' : 'https://maps.app.goo.gl/PzkbjhRBLTLjxLoZ7',
'ENBD - Abu Dhabi - Reem Mall Branch' : 'https://maps.app.goo.gl/4sQeMFds1ZBE58dv9',
'ENBD - Abu Dhabi - Yas Mall Branch' : 'https://maps.app.goo.gl/CL73mRWWXKV3bFbp6',
'ENBD - Abu Dhabi - Deerfields Mall Branch' : 'https://maps.app.goo.gl/2Q8njujTG5PNfq3N7',
'ENBD - Abu Dhabi - Al Ain Main Branch Hazza Bin Zayed Stadium Branch' : 'https://maps.app.goo.gl/2haC4dpS7HexZvXg9',
'ENBD - Abu Dhabi - Mussafah Branch' : 'https://maps.app.goo.gl/LNqocLQJRck7SyNPA',
'ENBD - Abu Dhabi - Madinati Mall Branch' : 'https://maps.app.goo.gl/saWed1JRoVRo4nDB8',
'ENBD - Ajman - Ajman City Center Branch' : 'https://maps.app.goo.gl/HXihADdWe9kqv5PN6',
'ENBD - Ajman - Ajman Main Branch' : 'https://maps.app.goo.gl/zEs6nR4JDGekuPgv5',
'ENBD - Dubai - Burj Al Arab Branch' : 'https://maps.app.goo.gl/HYKqEWUKdXw9LCZm6',
'ENBD - Dubai - Emirates Airline HQ Branch' : 'https://maps.app.goo.gl/Y8JWG1g8kPj3sDLS6',
'ENBD - Dubai - Dubai Design District Branch' : 'https://maps.app.goo.gl/3wzSdxgpzeSdhudc8',
'ENBD - Dubai - Dubai Airport T3 Branch' : 'https://maps.app.goo.gl/WPkF7y5ZsMs2Xzd36',
'ENBD - Dubai - Ras Al Khor Branch' : 'https://maps.app.goo.gl/CWYmcutef6PdsCcL7',
'ENBD - Dubai - Jumeirah Beach Residence Branch' : 'https://maps.app.goo.gl/QyYErEW6SsVD3uwG9',
'ENBD - Dubai - Dubai Mall Branch' : 'https://maps.app.goo.gl/AUhV5MxYH8vVQt4J9',
'ENBD - Dubai - Business Bay Branch' : 'https://maps.app.goo.gl/gTdJKALqLLotvDYM6',
'ENBD - Dubai - Deira City Center Branch' : 'https://maps.app.goo.gl/s8HyhAfv6WH8Vngi6',
'ENBD - Dubai - The Greens Branch' : 'https://maps.app.goo.gl/DkAAB3sYHupVENE58',
'ENBD - Dubai - Burj Khalifa Branch' : 'https://maps.app.goo.gl/ZeZ5LXaVc4JeSp7v8',
'ENBD - Dubai - Dubai Media City Branch' : 'https://maps.app.goo.gl/m2qWSBUCGB4kQ7H48',
'ENBD - Dubai - Al Muraqqabat Branch' : 'https://maps.app.goo.gl/gtewrfKbnbHLGoNz6',
'ENBD - Dubai - Al Barsha Branch' : 'https://maps.app.goo.gl/3JtBF9BQawd2ij4e6',
'ENBD - Dubai - Al Mankhool Branch' : 'https://maps.app.goo.gl/YHA2wqVgDB5yYWVB7',
'ENBD - Dubai - Dubai Festival City Branch' : 'https://maps.app.goo.gl/r2fug6CZTY5LZjsC9',
'ENBD - Dubai - Al Quoz Branch' : 'https://maps.app.goo.gl/CKioazU96vcKnRvAA',
'ENBD - Dubai - Dubai Silicon Oasis Branch' : 'https://maps.app.goo.gl/LSSibxEXc4qrecBh9',
'ENBD - Dubai - Hatta Branch' : 'https://maps.app.goo.gl/GuFZAfk8Sg22v6Vg8',
'ENBD - Dubai - Sheikh Zayed Road Branch' : 'https://maps.app.goo.gl/yZvLZnLVujyFUy6Q8',
'ENBD - Dubai - Wafi Mall Branch' : 'https://maps.app.goo.gl/9UsnnZWhXKo4cdyB7',
'ENBD - Dubai - Bank Street Branch' : 'https://maps.app.goo.gl/vHchRyisZf3nhsxQA',
'ENBD - Dubai - Dubai Hills Mall Branch' : 'https://maps.app.goo.gl/EYsPoQjg4Bzf7ZZR7',
'ENBD - Dubai - Al Aweer Branch' : 'https://maps.app.goo.gl/qWqkr6iCcohyHbpb6', #No reviews in the last month
'ENBD - Dubai - Emirates Towers Branch' : 'https://maps.app.goo.gl/qApVSPA17ezD1UAN6',
'ENBD - Dubai - Group Head Office Branch' : 'https://maps.app.goo.gl/JwmT3JWqiMjbg9Dc6',
'ENBD - Dubai - Jumeirah Branch' : 'https://maps.app.goo.gl/LpYPqQ12St8y5YRS9',
'ENBD - Dubai - Al Qusais Branch' : 'https://maps.app.goo.gl/K4TNSTky7fwR2jX66',
'ENBD - Dubai - Umm Suqeim Branch' : 'https://maps.app.goo.gl/qQECMWQyeAWfnqEu5',
'ENBD - Dubai - Deira Branch' : 'https://maps.app.goo.gl/U7CbbR7kr8XbrSfQ6',
'ENBD - Dubai - Mirdif City Center Branch' : 'https://maps.app.goo.gl/WSxs8dbU9WdSXyu97',
'ENBD - Dubai - Nad AL Shiba Branch' : 'https://maps.app.goo.gl/jkB1k9SW6umobVuJ9',
'ENBD - Dubai - Nad Al Shiba Mall Branch' : 'https://maps.app.goo.gl/tAhsFB79Xw8LfPBr9',
'ENBD - Dubai - Jumeirah Beach Road Branch' : 'https://maps.app.goo.gl/Wv3koz6qtV12xY9m6',
'ENBD - Dubai - Oud Metha Branch' : 'https://maps.app.goo.gl/mcLe7rqLusWE2CCZ8',
'ENBD - Dubai - Al Fahidi Branch' : 'https://maps.app.goo.gl/iisDVim9Jqf4JS7u9',
'ENBD - Dubai - Al Twar Branch' : 'https://maps.app.goo.gl/PeWiPBD5JZPsbJ6u8',
'ENBD - Dubai - Emirates Mall Branch' : 'https://maps.app.goo.gl/if5C4G8eKCuxc1oz5',
'ENBD - Dubai - Mizher Mall Branch' : 'https://maps.app.goo.gl/eJTZZ16Vda61dEXF7',
'ENBD - Dubai - Rashidiya Branch' : 'https://maps.app.goo.gl/RkQzTzaBpc4ZWDok8',
'ENBD - Dubai - Hamriya Branch' : 'https://maps.app.goo.gl/wLwrBAscLnEnVYok6',
'ENBD - Dubai - Al Satwa Branch' : 'https://maps.app.goo.gl/6UjAxE6kYC9RSbeG8',
'ENBD - Dubai - Ibn Battuta Mall Branch' : 'https://maps.app.goo.gl/5GLkpaPCjHvXKP9J7',
'ENBD - Dubai - Al Qiyadah Branch' : 'https://maps.app.goo.gl/xH3YjLzGVfehXpjA8',
'ENBD - Dubai - Jumeirah Lake Tower Branch' : 'https://maps.app.goo.gl/JDVj7dwdXDfiqKu17',
'ENBD - Dubai - Jebel Ali Branch' : 'https://maps.app.goo.gl/MGgzaEPCts3k8RHAA', #No reviews in the last month
'ENBD - Dubai - Junction Mall Branch' : 'https://maps.app.goo.gl/B4Q4cqomUheTsSXm9',
'ENBD - Dubai - Jumeirah Village Circle Branch' : 'https://maps.app.goo.gl/kXVkuGcDeWDrgMst6', #New branch in Feb'26
'ENBD - Fujairah - Fujairah Main Branch' : 'https://maps.app.goo.gl/KkW8NNZhTejvgXJg7',
'ENBD - Ras Al Khaimah - Ras AL Khaimah Corniche Branch' : 'https://maps.app.goo.gl/sghkTdTMmuqjDryc8',
'ENBD - Sharjah - Sharjah City Center Branch' : 'https://maps.app.goo.gl/j4RLXkt4EfBZhPuA7',
'ENBD - Sharjah - Sahara Mall Branch' : 'https://maps.app.goo.gl/eNqbYkdSk2osFe3f9',
'ENBD - Sharjah - Matajer Al Quoz Branch' : 'https://maps.app.goo.gl/2MihdZWaTWZCPtGJ9',
'ENBD - Sharjah - Sharjah Main Branch' : 'https://maps.app.goo.gl/oPDV95L5hqXW5Rks9',
'ENBD - Sharjah - Al Zahia City Centre Branch' : 'https://maps.app.goo.gl/BpeyWVV8UEc2YHGU9',
'ENBD - Sharjah - Sharjah AlSuyouh Branch' : 'https://maps.app.goo.gl/47KQ925r9b3gHWteA',
'ENBD - Umm Al Quwain - Umm Al Quwain Branch' : 'https://maps.app.goo.gl/sPiYK5z2GipEWQBy9',
# 72 ENBD

'EI - Abu Dhabi - Abu Dhabi Mall Branch' : 'https://maps.app.goo.gl/9G8zS7CBK5dyjoLFA',
'EI - Abu Dhabi - Abu Dhabi Branch' : 'https://maps.app.goo.gl/Kb716nnHVpgwM7jg9',
'EI - Abu Dhabi - Main Branch Abu Dhabi' : 'https://maps.app.goo.gl/VJciwUryvpKrdiYQ9',
'EI - Abu Dhabi - Bawabet Al Sharq Branch' : 'https://maps.app.goo.gl/JbegNseaCcFpWSAi6',
'EI - Abu Dhabi - Khalifa City Branch' : 'https://maps.app.goo.gl/fYmU6vLBdexRwbcT8',
'EI - Dubai - Al Mizher Branch' : 'https://maps.app.goo.gl/hvYAQs4bZTzgAAFQ9',
'EI - Dubai - Al Tawar Branch' : 'https://maps.app.goo.gl/7qS7SAa2jSD53YbP7',
'EI - Dubai - Al Barsha Mall Branch' : 'https://maps.app.goo.gl/aNeA8MBQFEb31WUB6',
'EI - Dubai - Diyafa Road Branch' : 'https://maps.app.goo.gl/FZnm6E8DLHBE8uk87',
'EI - Dubai - Healthcare City Branch' : 'https://maps.app.goo.gl/aVGW2HeG1tSZceDq9',
'EI - Dubai - Dubai Mall Branch' : 'https://maps.app.goo.gl/msMvdJAqCc1wk51E6',
'EI - Dubai - Dubai Land Dept Branch' : 'https://maps.app.goo.gl/bbbpwA3NmD6QwMe58',
'EI - Dubai - Nad Al Hamar Branch' : 'https://maps.app.goo.gl/TzTKayWcyGzfU5bA7',
'EI - Dubai - Sheik Zayed Road Branch' : 'https://maps.app.goo.gl/vRBzJJXhgXrn8TMh7',
'EI - Dubai - Baniyas Branch' : 'https://maps.app.goo.gl/crAy4o7wfSHURUMK8',
'EI - Dubai - Al Wasl Road Branch' : 'https://maps.app.goo.gl/nKrbRwSxmdWpMkZE6',
'EI - Dubai - Warqaa Mall Branch' : 'https://maps.app.goo.gl/crHBqGixmxTfAVuo7',
'EI - Dubai - Bur Dubai Branch' : 'https://maps.app.goo.gl/FAFwsG2hVDmKVDu6A',
'EI - Dubai - Nad El Shiba' : 'https://maps.app.goo.gl/CoCfFNDp9RXdhaY89',
'EI - Dubai - Jumairah Road Branch' : 'https://maps.app.goo.gl/jd8BDTim8DYJcNwd6',
'EI - Dubai - Dubai Hills Branch' : 'https://maps.app.goo.gl/jme29vqXDXHmGqxk6',
'EI - Dubai - Khawaneej Walk Branch' : 'https://maps.app.goo.gl/Jn1Ly4XZQcxDM4ox9',
'EI - Dubai - Al Barsha Heights Branch' : 'https://maps.app.goo.gl/fq131C9E2j6dzZaz6',
'EI - Dubai - Dubai Festival City Branch' : 'https://maps.app.goo.gl/3moCaAD8rp99B3or8',
'EI - Dubai - Silicon Central Mall Branch' : 'https://maps.app.goo.gl/6vuu1PKnCgpRyQHA7',
'EI - Sharjah - Khorfakkan Branch' : 'https://maps.app.goo.gl/HSYDWPqZBowCYrrr8', # Manual
'EI - Sharjah - Al Rahmaniya Mall Branch' : 'https://maps.app.goo.gl/1UThU3E38qnqHwUbA', 
'EI - Sharjah - Juriena Zero 6 Mall Branch' : 'https://maps.app.goo.gl/GeYAuP8H5Ba9d5DB7',
'EI - Sharjah - Halwan Branch' : 'https://maps.app.goo.gl/j7MvdJPwZqYUq2LH8',
'EI - Sharjah - Qasimiyah Branch' : 'https://maps.app.goo.gl/m6k7ww7FLAr49GaZ6',
'EI - Al Ain - Jimi Mall Branch' : 'https://maps.app.goo.gl/8LVTNN6JtiUHURtLA',
'EI - Al Ain - Al Ain Branch' : 'https://maps.app.goo.gl/h7frLLuY4sb23t1HA',
'EI - Fujairah - Fujairah Branch' : 'https://maps.app.goo.gl/4dmfmsJKQZSNcwK46',
'EI - Ras Al Khaimah - Ras Al Khaimah Branch' : 'https://maps.app.goo.gl/5dm1nfKfmvGBXC7f8',
'EI - Ajman - Ajman Kalifa Bin Zayed Branch' : 'https://maps.app.goo.gl/RABq6N9UqQjtJdTr6',
# 35 EI

'ADIB - Abu Dhabi  - Najda' : 'https://maps.app.goo.gl/GTNixCvAfwnxgdfT9', #No reviews in the last month
'ADIB - Abu Dhabi  - Al Wahda Mall' : 'https://maps.app.goo.gl/m1RZzP8bPPpHrsi37',
'ADIB - Abu Dhabi  - Abu Dhabi Police GHQ' : 'https://maps.app.goo.gl/94XMkLhhui97LRd88', #No reviews in the last month
'ADIB - Abu Dhabi  - Sheikh Zayed Main' : 'https://maps.app.goo.gl/kxg9Z9mmYSo46Rxg7',
'ADIB - Abu Dhabi  - Sheikh Khalifa Energy Complex' : 'https://maps.app.goo.gl/NeSNk7iHvkXAzN7t8', #No reviews in the last month
'ADIB - Abu Dhabi  - ADIA Cash Office' : 'https://maps.app.goo.gl/1iBWaDFLaXXKYFx6A', #No reviews in the last month
'ADIB - Abu Dhabi  - Al Bateen' : 'https://maps.app.goo.gl/19JjiMa7hwkzMtyP7',
'ADIB - Abu Dhabi  - Marina Mall' : 'https://maps.app.goo.gl/zj5icxDsTf629pzp9', #No reviews in the last month
'ADIB - Abu Dhabi  - Nation Towers' : 'https://maps.app.goo.gl/chmgWSNjH1TvH3Eb9',
'ADIB - Abu Dhabi  - Abu Dhabi Judicial Dept.' : 'https://maps.app.goo.gl/kkpeGF55KCvzywji8', #No reviews in the last month
'ADIB - Abu Dhabi  - Baniyas' : 'https://maps.app.goo.gl/fYqTCTxSXv9CgqVo9',
'ADIB - Abu Dhabi  - Mussafah' : 'https://maps.app.goo.gl/bwhBVTnwpqE5AkrR9',
'ADIB - Abu Dhabi  - Dalma Mall' : 'https://maps.app.goo.gl/guDHfqha3ehd3RNN6',
'ADIB - Abu Dhabi  - Khalifa A City' : 'https://maps.app.goo.gl/RsydGQyMqEG674SLA',
'ADIB - Abu Dhabi  - Bawabat Al Sharq' : 'https://maps.app.goo.gl/dm96WN1DdKEyUwao8',
'ADIB - Abu Dhabi  - Shahama' : 'https://maps.app.goo.gl/h5Y2ypu9vk9torzS7',
'ADIB - Abu Dhabi  - Yas Mall' : 'https://maps.app.goo.gl/C1nmvP5xKn1GCG4c6',
'ADIB - Abu Dhabi  - Madinat Zayed' : 'https://maps.app.goo.gl/2Fm9Dt2N89CxCSRr9',
'ADIB - Abu Dhabi  - Al Silaa' : 'https://maps.app.goo.gl/jMe7MoQwsb8K323bA', #No reviews in the last month
'ADIB - Abu Dhabi  - Al Marfaa' : 'https://maps.app.goo.gl/t9XGuVQfF1KYVGij7',
'ADIB - Abu Dhabi  - Delma Island' : 'https://maps.app.goo.gl/W9e5fz13ZMcBGriAA', #No reviews in the last month
'ADIB - Abu Dhabi  - Liwa' : 'https://maps.app.goo.gl/1nimPGmnsMX7HwGD9', #No reviews in the last month
'ADIB - Abu Dhabi  - Ghayathi' : 'https://maps.app.goo.gl/ec2Yuainrzoau9WS6',
'ADIB - Abu Dhabi  - Al Ain' : 'https://maps.app.goo.gl/vEKm5SLqnFtfUCye7',
'ADIB - Abu Dhabi  - Al Jimi' : 'https://maps.app.goo.gl/sx1zkyC8EW4dFhhn9',
'ADIB - Abu Dhabi  - Al Yahar' : 'https://maps.app.goo.gl/HNuJddDAfrdDA74j9', 
'ADIB - Abu Dhabi  - Al Wagan' : 'https://maps.app.goo.gl/qyZqdk46U5JNWkgY8', #No reviews in the last month
'ADIB - Abu Dhabi  - Oud Al Tobba' : 'https://maps.app.goo.gl/Y58fu7AJ2p1jMm9y9', #No reviews in the last month
'ADIB - Abu Dhabi  - Al Bawadi Mall' : 'https://maps.app.goo.gl/QDYSFQ1pCwuPkXwm7',
'ADIB - Abu Dhabi  - Makani Mall' : 'https://maps.app.goo.gl/Gfo5KMvM3J2rjYZQ7',
'ADIB - Abu Dhabi  - Ruwais Mall' : 'https://maps.app.goo.gl/awWGL5Rf9jgSUHyF6',
'ADIB - Dubai  - Sh. Zayed Road' : 'https://maps.app.goo.gl/SMtF2mKffz4B83C87',
'ADIB - Dubai  - ArencoDIC' : 'https://maps.app.goo.gl/9mNKLo95ko3HTrqM6',
'ADIB - Dubai  - Dubai Mall' : 'https://maps.app.goo.gl/d2LRGTV1qaqgzYtj7',
'ADIB - Dubai  - Second of December' : 'https://maps.app.goo.gl/CaqogmFa6yDBFqT47',
'ADIB - Dubai  - Al Barsha' : 'https://maps.app.goo.gl/SjyULqX8uNcZ9N4d7',
'ADIB - Dubai  - Nad Al Hamar' : 'https://maps.app.goo.gl/tGSEUXF5wEpxTMJX7',
'ADIB - Dubai  - Al Muhaisnah (Etihad Mall)' : 'https://maps.app.goo.gl/neJq3xMFATsUFjG9A',
'ADIB - Dubai  - Al Quasis' : 'https://maps.app.goo.gl/X5smnQTkVMcgeUAb9',
'ADIB - Dubai  - Deira Branch' : 'https://maps.app.goo.gl/YA5r8q3mnXRnD2wD8',
'ADIB - Dubai  - Nad Al Sheba Avenue Mall' : 'https://maps.app.goo.gl/Nsy4iCZJZY6oWbds9',
'ADIB - Sharjah  - Sharjah' : 'https://maps.app.goo.gl/pCKGaaWmGKYffW2d7',
'ADIB - Sharjah  - Zawaya Walk' : 'https://maps.app.goo.gl/eCmag35g5dHTAyuT8',
'ADIB - Sharjah  - Al Rahmania Mall' : 'https://maps.app.goo.gl/LVq81G2rmpZksfWh9',
'ADIB - Sharjah  - Al Buhairah' : 'https://maps.app.goo.gl/KsMXWEwcxbGUsUNG8',
'ADIB - Sharjah  - Al Juraina' : 'https://maps.app.goo.gl/qciKJWTyEd5t7X8W8',
'ADIB - Sharjah  - Al Dhaid' : 'https://maps.app.goo.gl/1axn9wQUDQ2NZKWA9', #No reviews in the last month
'ADIB - Sharjah  - Kalba' : 'https://maps.app.goo.gl/whmMNbmna9vC7ifr7', #No reviews in the last month
'ADIB - Fujairah  - Fujairah' : 'https://maps.app.goo.gl/a5QNu2vnfTDoJjN26',
'ADIB - Fujairah  - Dibba' : 'https://maps.app.goo.gl/53Q9KNjjLCoLoW14A',
'ADIB - Fujairah  - Fujairah City Centre' : 'https://maps.app.goo.gl/irWorFebmiStsetZ7',
'ADIB - Ras Al Khaimah  - RAK Airport' : 'https://maps.app.goo.gl/Ta9uZk47hd1GUMzK9', #No reviews in the last month
'ADIB - Ras Al Khaimah  - Al Hamra Mall' : 'https://maps.app.goo.gl/Mu3B1uLWqm9qK19E7',
'ADIB - Umm Al Quwain  - Umm Al Qaiwain' : 'https://maps.app.goo.gl/7znqXjEMftiRVSf67',
# 54 ADIB
    
'ADCB - Abu Dhabi  - ADCB Head Office' : 'https://maps.app.goo.gl/v6ZgpDrCuMpCE1kF8',
'ADCB - Abu Dhabi  - Al Hosn' : 'https://maps.app.goo.gl/eyhivJ1KZ1uyhUR56',
'ADCB - Abu Dhabi  - Khalidiya Mall' : 'https://maps.app.goo.gl/qaCoHsVNTTsSJ2A48',
'ADCB - Abu Dhabi  - GASCO Head Office' : 'https://maps.app.goo.gl/Ykk5h6wkBzMoP9WN9',
'ADCB - Abu Dhabi  - Madinat Zayed' : 'https://maps.app.goo.gl/i2x3ujBVw9j5rYcM9',
'ADCB - Abu Dhabi  - Ruwais' : 'https://maps.app.goo.gl/B8Txxg5WVH7ovX319',
'ADCB - Abu Dhabi  - Mussafah' : 'https://maps.app.goo.gl/xYKCzvDGimVWVLn7A',
'ADCB - Abu Dhabi  - Ghayathi' : 'https://maps.app.goo.gl/cTpSvDBDV4a47E9DA',
'ADCB - Abu Dhabi  - Baya Al Sila' : 'https://maps.app.goo.gl/ucz5D6saR45gQe8L6',
'ADCB - Abu Dhabi  - Dalma Mall' : 'https://maps.app.goo.gl/eJtBTk7f2nxA7pSi9',
'ADCB - Abu Dhabi  - Khalifa City A' : 'https://maps.app.goo.gl/ypm7TuYEfMjWoozU6',
'ADCB - Abu Dhabi  - Abu Dhabi Mall' : 'https://maps.app.goo.gl/HBWyAHCm4R8wnPnv8',
'ADCB - Abu Dhabi  - Bawabat Al Sharq Mall' : 'https://maps.app.goo.gl/B2ygzgCSY2iRhG4B9',
'ADCB - Abu Dhabi  - ADIA' : 'https://maps.app.goo.gl/KgLoJs7Z8bH4Gguu8',
'ADCB - Abu Dhabi  - Galleria Mall' : 'https://maps.app.goo.gl/GEBhnkBCodtF5VWh9',
'ADCB - Abu Dhabi  - Yas Mall' : 'https://maps.app.goo.gl/bqdj4YEfVK8sDSREA',
'ADCB - Abu Dhabi  - Al Ain Main' : 'https://maps.app.goo.gl/x5VZZN7Xa9uSriMcA',
'ADCB - Abu Dhabi  - Al Yahar' : 'https://maps.app.goo.gl/KaXKKtsagx97wnC26',
'ADCB - Abu Dhabi  - Hazza Bin Zayed Stadium' : 'https://maps.app.goo.gl/xjN4YaxRfHVq3kWe8',
'ADCB - Abu Dhabi  - Al Murabaa Branch' : 'https://maps.app.goo.gl/bRq4PqWwH225JZLSA', 
'ADCB - Abu Dhabi  - Reem Mall' : 'https://maps.app.goo.gl/iXwwJbFi1zofJ5yi7',
'ADCB - Dubai  - Al Rigga Street' : 'https://maps.app.goo.gl/qjNz7R29DwHgB85v5',
'ADCB - Dubai  - Karama' : 'https://maps.app.goo.gl/z223kvQGtdv58rH3A',
'ADCB - Dubai  - Deira City Centre' : 'https://maps.app.goo.gl/C75HMwyVrXvZomyYA',
'ADCB - Dubai  - Al Ittihad' : 'https://maps.app.goo.gl/N5rWihqcDE4iHeHN8',
'ADCB - Dubai  - Mall of the Emirates' : 'https://maps.app.goo.gl/u2x4o7DJYeD56dEx6',
'ADCB - Dubai  - Dubai Mall' : 'https://maps.app.goo.gl/X6BkhLdgjH5g96ZH8',
'ADCB - Dubai  - Arabian Center' : 'https://maps.app.goo.gl/ebEGaSSaNEsg4mdi6',
'ADCB - Dubai  - Khalid Bin Waleed' : 'https://maps.app.goo.gl/jN6AQeqag5azo7T57',
'ADCB - Dubai  - Business Bay' : 'https://maps.app.goo.gl/rTY6ZBQ96Q6DQKRp6',
'ADCB - Dubai  - Rashidiya' : 'https://maps.app.goo.gl/HeEWS9uc4WuKK87s6', 
'ADCB - Dubai  - Al Bustan' : 'https://maps.app.goo.gl/KzJfNDc1RZb9rZor9',
'ADCB - Sharjah  - Sharjah Main' : 'https://maps.app.goo.gl/a4NGPRVg7WUnMtwb8',
'ADCB - Sharjah  - Al Zahia City Centre' : 'https://maps.app.goo.gl/kTmgRwekqcdQJVD47',
'ADCB - Sharjah  - Al Buhaira' : 'https://maps.app.goo.gl/gjZ4u3kiB9WQLWV77',
'ADCB - Sharjah  - Dhaid' : 'https://maps.app.goo.gl/Jeb2xBv9jrWwF6mK8',
'ADCB - Fujairah  - Fujairah' : 'https://maps.app.goo.gl/no8pNF84rCR3D6WXA',
'ADCB - Fujairah  - Dibba' : 'https://maps.app.goo.gl/muDuo7DTz5XFt9Pp7',
'ADCB - Ras Al Khaimah  - Ras Al Khaimah' : 'https://maps.app.goo.gl/NWdaaWy5GYBrGKk9A',
'ADCB - Ajman  - Ajman' : 'https://maps.app.goo.gl/tQS7DGkAzMSXbqSg6',
'ADCB - Ajman  - Al Jurf' : 'https://maps.app.goo.gl/tJJdWMfgxzPDacac6',
# 41 ADCB
    
'FAB - Abu Dhabi  - Reem Mall' : 'https://maps.app.goo.gl/ryC8QFhCxLJE2Hgi8',
'FAB - Abu Dhabi  - Bateen' : 'https://maps.app.goo.gl/vzeKywbsyuxbXaJ59',
'FAB - Abu Dhabi  - ADIA Branch' : 'https://maps.app.goo.gl/VE374EdtixfZvq9U6',#No reviews in the last month
'FAB - Abu Dhabi  - FAB Islamic Abu Dhabi' : 'https://maps.app.goo.gl/xqcmEgKbswu2pUz27', 
'FAB - Abu Dhabi  - New Shahama Branch' : 'https://maps.app.goo.gl/kKP97DJaReDNNnFT6',
'FAB - Abu Dhabi  - Business Park' : 'https://maps.app.goo.gl/8JvrJ62BfchBaU5g7',
'FAB - Abu Dhabi  - Masdar City' : 'https://maps.app.goo.gl/ZdMwBB3Cq7wt6Hzq5',
'FAB - Abu Dhabi  - Emirates Palace Hotel' : 'https://maps.app.goo.gl/fM7NGD8dD9NdLCZM7', 
'FAB - Abu Dhabi  - Das Island' : 'https://maps.app.goo.gl/eVwNi6K4JUgZPy1u6',
'FAB - Abu Dhabi  - Corniche' : 'https://maps.app.goo.gl/DyGQoYrV15FAStxq7',
'FAB - Abu Dhabi  - Sweihan' : 'https://maps.app.goo.gl/zwthMdjEn6N69uvR8',
'FAB - Abu Dhabi  - Sheikh Rashid Road' : 'https://maps.app.goo.gl/WVdXiLt8eHx3jX396',
'FAB - Abu Dhabi  - ZADCO Cash Office' : 'https://maps.app.goo.gl/iHRPdrX11U8dFwfY7',  
'FAB - Abu Dhabi  - Mussafah' : 'https://maps.app.goo.gl/ELknFVP8ReQeumhv8',
'FAB - Abu Dhabi  - Al Khubeirah' : 'https://maps.app.goo.gl/zDVrWkpgocgF65LXA',
'FAB - Abu Dhabi  - Baniyas Branch' : 'https://maps.app.goo.gl/RpAzEbMR2R9a6W1ZA',
'FAB - Abu Dhabi  - Between Two Bridges' : 'https://maps.app.goo.gl/6VNzqbLZBsJnCm6o8',
'FAB - Abu Dhabi  - Salam Street' : 'https://maps.app.goo.gl/Dnj4HqYbEhr3nFaK6',
'FAB - Abu Dhabi  - Etihad' : 'https://maps.app.goo.gl/m27np13Kxtc4Bre87',
'FAB - Abu Dhabi  - Yas Mall' : 'https://maps.app.goo.gl/nKT1tQP8gm8yz2f19',
'FAB - Abu Dhabi  - Dalma Mall' : 'https://maps.app.goo.gl/dEJFWDtePbBdbFZq6',
'FAB - Abu Dhabi  - Abu Dhabi Mall' : 'https://maps.app.goo.gl/GA9YpNiwkcKHXa9T8',
'FAB - Abu Dhabi  - Al Mushrif Mall' : 'https://maps.app.goo.gl/91mePHYVPVsihQBr7',
'FAB - Abu Dhabi  - FAB One Tower' : 'https://maps.app.goo.gl/kKa7QVn56zSam3u9A',
'FAB - Abu Dhabi  - NPCC Cash Office' : 'https://maps.app.goo.gl/9XewehM35x3wMGbt8', 
'FAB - Abu Dhabi  - Al Maqam' : 'https://maps.app.goo.gl/wvCzSvAAZjpkpBH58',
'FAB - Abu Dhabi  - Al Ain New' : 'https://maps.app.goo.gl/ZpktFAEbAPuZ2Gbg6',
'FAB - Abu Dhabi  - Al Ain Civic Center' : 'https://maps.app.goo.gl/MF2uiYhxqUeGiJYG8',
'FAB - Abu Dhabi  - Oud Al Touba' : 'https://maps.app.goo.gl/aGBBjK9TqWbRga8H8',
'FAB - Abu Dhabi  - Al Ain Mall' : 'https://maps.app.goo.gl/uFDQH52Gx4mjpTzR9',
'FAB - Abu Dhabi  - Wahat Al Hili Mall' : 'https://maps.app.goo.gl/xFCJSSrvBKQuFUuYA', #No reviews in the last month
'FAB - Abu Dhabi  - FAB Islamic Al Ain' : 'https://maps.app.goo.gl/R87y91nAt3QizuAH9',
'FAB - Abu Dhabi  - Liwa Tamm Centre' : 'https://maps.app.goo.gl/gp4vHUkXtBpv5jEt7', #No reviews in the last month
'FAB - Abu Dhabi  - Ruwais' : 'https://maps.app.goo.gl/Zig93ZkzhCgwkXUA7', #No reviews in the last month
'FAB - Abu Dhabi  - Ghayathi' : 'https://maps.app.goo.gl/bu9fNL7yxnqZSFNE6',
'FAB - Abu Dhabi  - Madinat Zayed' : 'https://maps.app.goo.gl/5vZbfRGyHZBzRHJb6',
'FAB - Dubai  - Dubai Hills Mall' : 'https://maps.app.goo.gl/j7Uz8kqVJa1ibFBW6',
'FAB - Dubai  - FAB Islamic Dubai' : 'https://maps.app.goo.gl/QViLrMTfAFPmhNdTA',
'FAB - Dubai  - Avenue Mall' : 'https://maps.app.goo.gl/WiXoroT6fZXyaRkr7',
'FAB - Dubai  - Nakheel Mall' : 'https://maps.app.goo.gl/ur4NwnBpfnAUVKhr5',
'FAB - Dubai  - Bur Dubai' : 'https://maps.app.goo.gl/wTuSjSJ2QiraZFwt9',
'FAB - Dubai  - Sheikh Zayed Road' : 'https://maps.app.goo.gl/DTnq2HhmTzPUsE268',
'FAB - Dubai  - Jebel Ali' : 'https://maps.app.goo.gl/PHsdUZUdTPusoMU19',
'FAB - Dubai  - Abu Baker Al Siddique' : 'https://maps.app.goo.gl/zgfFoutR45sZ7ap29',
'FAB - Dubai  - Rolex Tower' : 'https://maps.app.goo.gl/LznFtHgitVqqtKxY8',
'FAB - Dubai  - Dubai Mall' : 'https://maps.app.goo.gl/s19CE95jSDKWPcVx6',
'FAB - Dubai  - Mall of the Emirates' : 'https://maps.app.goo.gl/K6htVa4pLz4a2nSr7',
'FAB - Dubai  - Mirdiff City Center' : 'https://maps.app.goo.gl/oK8kBYCoj8BXHA526',
'FAB - Sharjah  - Al Zahia City Center' : 'https://maps.app.goo.gl/YbjLUD6bBpDnhX7x5',
'FAB - Sharjah  - Sahara Center' : 'https://maps.app.goo.gl/J6bqwo8iZZvQHGZf6',
'FAB - Sharjah  - Al Madam' : 'https://maps.app.goo.gl/qeYxha4TUEzMX2kT7',
'FAB - Sharjah  - Sharjah' : 'https://maps.app.goo.gl/S4LenbWJBZnZZXWe7',
'FAB - Sharjah  - Kalba' : 'https://maps.app.goo.gl/8yTMPH9Zb5oCBM4e8',
'FAB - Sharjah  - Khorfakkan' : 'https://maps.app.goo.gl/vnohUv5gMgXV8aTh8', #No reviews in the last month
'FAB - Fujairah  - Fujairah' : 'https://maps.app.goo.gl/J9GAEkMoTrghW7aa7',
'FAB - Fujairah  - Dibba' : 'https://maps.app.goo.gl/AGcApsCsSN8MZa538',
'FAB - Ras Al Khaimah  - Ras Al Khaimah Corniche' : 'https://maps.app.goo.gl/ktcYmDyg8CCWjQPu9', #No reviews in the last month
'FAB - Ras Al Khaimah  - FAB Islamic Ras Al Khaimah' : 'https://maps.app.goo.gl/8B9JxQCg7ywXcCMk6', #No reviews in the last month
'FAB - Ajman  - Ajman Branch' : 'https://maps.app.goo.gl/ASMJGfsAJxMeREkf7',
'FAB - Umm Al Quwain  - Umm Al Quwain' : 'https://maps.app.goo.gl/zeFYpw88yrTFmvG66',
# 60 FAB  

'RAK - Abu Dhabi  - Khalidiya Branch' : 'https://maps.app.goo.gl/eztKNHAPS9mi4AZy6',
'RAK - Abu Dhabi  - Musaffah' : 'https://maps.app.goo.gl/ncg3rmvcSqHqoCjm9',
'RAK - Abu Dhabi  - Al Ain' : 'https://maps.app.goo.gl/tE99aHnFdTr9gcbg6',
'RAK - Abu Dhabi  - Elite Centre' : 'https://maps.app.goo.gl/S2HcUjkYk624YNCp6', #No reviews in the last month
'RAK - Dubai  - Al Qusais' : 'https://maps.app.goo.gl/L7LC3yzGT6AG5J6M7',
'RAK - Dubai  - Umm Hurair' : 'https://maps.app.goo.gl/wwNvXystvhczM3Dd8',
'RAK - Dubai  - Deira Maktoum' : 'https://maps.app.goo.gl/ZztKqUMEZ2iuExBH7',
'RAK - Dubai  - Gold Souq' : 'https://maps.app.goo.gl/oEg93sdPf1R9hRLv5',
'RAK - Dubai  - Emaar' : 'https://maps.app.goo.gl/kMokb61CKFPkPwJc8',
'RAK - Dubai  - Dragon Mart' : 'https://maps.app.goo.gl/xgRMA7M8RXsyuHGy7',
'RAK - Dubai  - Al Quoz' : 'https://maps.app.goo.gl/PpSyejGHi9sEz5As8',
'RAK - Dubai  - Motor City' : 'https://maps.app.goo.gl/GcDy4FXJb816itnt9',
'RAK - Sharjah  - King Faisal' : 'https://maps.app.goo.gl/CkxTtrcyKkjVfQt19',
'RAK - Fujairah  - Fujairah' : 'https://maps.app.goo.gl/n1JeG9TeGBx37TeE6',
'RAK - Ras Al Khaimah  - Al Dhait' : 'https://maps.app.goo.gl/LNQDnCgLteXNLTW96',
'RAK - Ras Al Khaimah  - Al Hamra' : 'https://maps.app.goo.gl/Rn4uQUiWJ5NFxGCv6',
'RAK - Ras Al Khaimah  - Al Mannei' : 'https://maps.app.goo.gl/84mPBfGbLVaRVMXt6',
'RAK - Ras Al Khaimah  - Al Nakheel' : 'https://maps.app.goo.gl/sCNh3zCfmGKR5yWy8',
'RAK - Ajman  - Ajman' : 'https://maps.app.goo.gl/Qv34QwuQB67UVHQL8',
# 19 RAK
    
'Mashreq - Abu Dhabi  - Abu Dhabi Main' : 'https://maps.app.goo.gl/ECLPw8sYP5eswfTN7',
'Mashreq - Abu Dhabi  - Al Ain Main EBSU' : 'https://maps.app.goo.gl/sUUdbjh7AYkJrhwb6',
'Mashreq - Dubai  - Dubai Festival City' : 'https://maps.app.goo.gl/VwYmhViWHJNEEabQ8',
'Mashreq - Dubai  - Dubai Internet City' : 'https://maps.app.goo.gl/K2EeFUD9sXRVrr1BA',
'Mashreq - Dubai  - Dubai Mall' : 'https://maps.app.goo.gl/6iuse9EudokkSupM6',
'Mashreq - Dubai  - Mirdif City Center' : 'https://maps.app.goo.gl/n5fCK3XgvjAbSUPXA', #No reviews in the last month
'Mashreq - Dubai  - Mall of the Emirates' : 'https://maps.app.goo.gl/7yVNfW2wYafMpiEq9',
'Mashreq - Dubai  - Muraqqabat' : 'https://maps.app.goo.gl/D2o1rrmP8ej6cH2F6',
'Mashreq - Dubai  - Rigga' : 'https://maps.app.goo.gl/aT6HAvZrfApTe2eu6',
'Mashreq - Sharjah  - Sahara Centre' : 'https://maps.app.goo.gl/E8sno89b2TBtoxd18',
'Mashreq - Sharjah  - Sharjah Industrial Area' : 'https://maps.app.goo.gl/if3gjg4S5vm4CYpo9',
'Mashreq - Sharjah  - King Abdul Aziz' : 'https://maps.app.goo.gl/J71TW3mry2cgQRRL6',
'Mashreq - Ajman  - Ajman' : 'https://maps.app.goo.gl/NpRrimcWbdnNqxNVA',
'Mashreq - Ras Al Khaimah  - Al Nakheel' : 'https://maps.app.goo.gl/MsjpXSmsXJQM7b928',
# 14 MASHREQ
    
'CBD - Abu Dhabi  - Zayed the First' : 'https://maps.app.goo.gl/2fjjRYE6kmtw4ouW8',
'CBD - Dubai  - Main Dubai Branch' : 'https://maps.app.goo.gl/pjaJWP89qnYBvz179',
'CBD - Dubai  - Sheikh Zayed Road' : 'https://maps.app.goo.gl/Gd18hyNy2UNLriSt7',
'CBD - Sharjah  - Sharjah' : 'https://maps.app.goo.gl/6NNTuXsMmNAThsjv5',
'CBD - Ras Al Khaimah  - Ras Al Khaimah' : 'https://maps.app.goo.gl/cSwn6tdkt8QgRA1t8', #No reviews in the last month
# 5 CBD
    
'DIB - Abu Dhabi  - Bawabat Al Sharq Mall' : 'https://maps.app.goo.gl/nMxx6LhTpA59DL3f8',
'DIB - Abu Dhabi  - Abu Dhabi Main' : 'https://maps.app.goo.gl/dW147N8deFxmyaFn9',
'DIB - Abu Dhabi  - Al Dharfa Mall' : 'https://maps.app.goo.gl/iLkZUeuVAuiTn7wp7', #No reviews in the last month
'DIB - Abu Dhabi  - Al Wahda Mall' : 'https://maps.app.goo.gl/CjeXKs2oW7ikfuxZ6',
'DIB - Abu Dhabi  - Al Muroor' : 'https://maps.app.goo.gl/ywKDhV8NPmdk3PEh9',
'DIB - Abu Dhabi  - Al Salam' : 'https://maps.app.goo.gl/foJGmk7SuqzEo1ra8',
'DIB - Abu Dhabi  - Dalma Mall' : 'https://maps.app.goo.gl/JFv9SmTkL6h1gnKo6',
'DIB - Abu Dhabi  - Deerfields Mall' : 'https://maps.app.goo.gl/GurCgYZyukBfErH5A',
'DIB - Abu Dhabi  - Al Ain' : 'https://maps.app.goo.gl/VPeNq4gghoYD9NcPA',
'DIB - Abu Dhabi  - Al Aliah Mall' : 'https://maps.app.goo.gl/wPK7U2vNXUdR6m1M7', #No reviews in the last month
'DIB - Abu Dhabi  - Al jimi' : 'https://maps.app.goo.gl/n9cqHpUVVgkQkTqA7',
'DIB - Abu Dhabi  - Al Ain Mall' : 'https://maps.app.goo.gl/Uxy6qba8e3gqq9EF6',
'DIB - Dubai  - Al Maktoum' : 'https://maps.app.goo.gl/PB6k4o7pLxT85NXC7',
'DIB - Dubai  - Bur Dubai' : 'https://maps.app.goo.gl/U8mEc8HHarp1tNMp8',
'DIB - Dubai  - Mirdif City Center' : 'https://maps.app.goo.gl/QmHJDhjqMoBtaKQY6',
'DIB - Dubai  - Mall of the Emirates' : 'https://maps.app.goo.gl/BReCGYXzLnDNiyoZ7',
'DIB - Dubai  - Muhaisnah Al Ittihad' : 'https://maps.app.goo.gl/h71CMjdyY7iExTQX8',
'DIB - Dubai  - Emirates HQ' : 'https://maps.app.goo.gl/XKgvb8GxsasbN3Sk8',
'DIB - Dubai  - Al Nahda' : 'https://maps.app.goo.gl/kCyD1Hezg9qpA1359',
'DIB - Dubai  - Umm Suqeim' : 'https://maps.app.goo.gl/zAxvzsVyXeAieRvX9',
'DIB - Dubai  - Dubai Hills' : 'https://maps.app.goo.gl/vWqxUxe6zQ8vXa7P7',
'DIB - Dubai  - Al Twar' : 'https://maps.app.goo.gl/saxt7YgRyWEbzg448',
'DIB - Dubai  - Oud Mehta' : 'https://maps.app.goo.gl/KvMceqrTWvuLwvaA9',
'DIB - Dubai  - Ibn Battuta Mall' : 'https://maps.app.goo.gl/FXB1dXYAgNpFig6q7',
'DIB - Dubai  - Al Barsha Al Ittihad Mall' : 'https://maps.app.goo.gl/f4Mx5gLQUbZNK2NJ8',
'DIB - Dubai  - Al Lisaili' : 'https://maps.app.goo.gl/JwqXXu6kn21pBmoi9', #No reviews in the last month
'DIB - Dubai  - Dubai Internet City' : 'https://maps.app.goo.gl/wv7FnGy23mj3gpTs5',
'DIB - Dubai  - Sheikh Zayed Road' : 'https://maps.app.goo.gl/JuxuuB66ZF9fDmxaA',
'DIB - Dubai  - Dubai Mall' : 'https://maps.app.goo.gl/35yCGYic6XMevmrB7',
'DIB - Dubai  - Jumeirah Ladies Branch' : 'https://maps.app.goo.gl/fp24sCrmsqp4JrS96',
'DIB - Dubai  - Madinate Badr' : 'https://maps.app.goo.gl/7qRumYfqX2fmg4uP7',
'DIB - Fujairah  - Fujairah Branch' : 'https://maps.app.goo.gl/5rHfRManjAvgosFGA',
'DIB - Fujairah  - Dibba Fujairah' : 'https://maps.app.goo.gl/YjZit2yYbBJS7H4HA', #No reviews in the last month
'DIB - Ras Al Khaimah  - Ras Al Khaimah' : 'https://maps.app.goo.gl/D3CvwfkZoKiRMLz86', #No reviews in the last month 
'DIB - Ras Al Khaimah  - Khuzam' : 'https://maps.app.goo.gl/w6ZKTn4tPM75v12h7',
'DIB - Ras Al Khaimah  - Julfar' : 'https://maps.app.goo.gl/Y6GDUo5T6m2B8yANA', #No reviews in the last month
'DIB - Sharjah  - Al Madam' : 'https://maps.app.goo.gl/6QiVebCdc5dkagcx5', #No reviews in the last month
'DIB - Sharjah  - Sharjah Clock Tower' : 'https://maps.app.goo.gl/V4smnKKkp9DiDMii9',
'DIB - Sharjah  - Tasjeel Village' : 'https://maps.app.goo.gl/4iLoY4jLed5KfFKH8',
'DIB - Sharjah  - Sharjah Ladies Branch' : 'https://maps.app.goo.gl/f6iUrCR2eMRXfyib7',
'DIB - Sharjah  - Al Dhaid Branch' : 'https://maps.app.goo.gl/R1u4QmHLNpBzdMBP7',
'DIB - Sharjah  - Kalba' : 'https://maps.app.goo.gl/w4uvyrTcRKSWDEtb9', #No reviews in the last month
'DIB - Sharjah  - KhorFakkan Branch' : 'https://maps.app.goo.gl/Cp1t4oUBCC3wxA899',
'DIB - Sharjah  - Al Qarrayn' : 'https://maps.app.goo.gl/e2prE4RU4ixn2EoU8',
'DIB - Sharjah  - AL Zahia City Center' : 'https://maps.app.goo.gl/rcYFLJ9EwnuTiW4AA',
'DIB - Umm Al Quwain  - Mall of UAQ' : 'https://maps.app.goo.gl/8BUkwzjoTRZve7Ym6',
'DIB - Ajman  - Ajman' : 'https://maps.app.goo.gl/kEhbhNJebxxbXie5A',
'DIB - Ajman  - Humaidiya' : 'https://maps.app.goo.gl/pKnhMrnjj4ZyDask9'

}

region_to_branch = {
    'Abu Dhabi & Al Ain Region': [
        'ENBD - Abu Dhabi - Abu Dhabi Main Office branch',
        'ENBD - Abu Dhabi - Electra Street Branch',
        'ENBD - Abu Dhabi - Tourist Club Branch',
        'ENBD - Abu Dhabi - Al Ain Khalifa street Branch',
        'ENBD - Abu Dhabi - Dalma Mall Branch',
        'ENBD - Abu Dhabi - Khalifa Branch',
        'ENBD - Abu Dhabi - Khalidiya Branch',
        'ENBD - Abu Dhabi - Reem Mall Branch',
        'ENBD - Abu Dhabi - Yas Mall Branch',
        'ENBD - Abu Dhabi - Deerfields Mall Branch',
        'ENBD - Abu Dhabi - Al Ain Main Branch Hazza Bin Zayed Stadium Branch',
        'ENBD - Abu Dhabi - Mussafah Branch',
        'ENBD - Abu Dhabi - Madinati Mall Branch'
    ],
    'Bur Dubai Region': [
        'ENBD - Dubai - Dubai Design District Branch',
        'ENBD - Dubai - Dubai Mall Branch',
        'ENBD - Dubai - Business Bay Branch',
        'ENBD - Dubai - Burj Khalifa Branch',
        'ENBD - Dubai - Al Mankhool Branch',
        'ENBD - Dubai - Sheikh Zayed Road Branch',
        'ENBD - Dubai - Wafi Mall Branch',
        'ENBD - Dubai - Bank Street Branch',
        'ENBD - Dubai - Emirates Towers Branch',
        'ENBD - Dubai - Nad AL Shiba Branch',
        'ENBD - Dubai - Nad Al Shiba Mall Branch',
        'ENBD - Dubai - Oud Metha Branch',
        'ENBD - Dubai - Al Fahidi Branch',
        'ENBD - Dubai - Al Satwa Branch'
    ],
    'Deira Region': [
        'ENBD - Dubai - Emirates Airline HQ Branch',
        'ENBD - Dubai - Dubai Airport T3 Branch',
        'ENBD - Dubai - Ras Al Khor Branch',
        'ENBD - Dubai - Deira City Center Branch',
        'ENBD - Dubai - Al Muraqqabat Branch',
        'ENBD - Dubai - Dubai Festival City Branch',
        'ENBD - Dubai - Dubai Silicon Oasis Branch',
        'ENBD - Dubai - Hatta Branch',
        'ENBD - Dubai - Al Aweer Branch',
        'ENBD - Dubai - Group Head Office Branch',
        'ENBD - Dubai - Al Qusais Branch',
        'ENBD - Dubai - Deira Branch',
        'ENBD - Dubai - Mirdif City Center Branch',
        'ENBD - Dubai - Al Twar Branch',
        'ENBD - Dubai - Mizher Mall Branch',
        'ENBD - Dubai - Rashidiya Branch',
        'ENBD - Dubai - Hamriya Branch',
        'ENBD - Dubai - Al Qiyadah Branch'
    ],
    'New Dubai Region': [
        'ENBD - Dubai - Burj Al Arab Branch',
        'ENBD - Dubai - Jumeirah Beach Residence Branch',
        'ENBD - Dubai - The Greens Branch',
        'ENBD - Dubai - Dubai Media City Branch',
        'ENBD - Dubai - Al Barsha Branch',
        'ENBD - Dubai - Al Quoz Branch',
        'ENBD - Dubai - Dubai Hills Mall Branch',
        'ENBD - Dubai - Jumeirah Branch',
        'ENBD - Dubai - Umm Suqeim Branch',
        'ENBD - Dubai - Jumeirah Beach Road Branch',
        'ENBD - Dubai - Emirates Mall Branch',
        'ENBD - Dubai - Ibn Battuta Mall Branch',
        'ENBD - Dubai - Jumeirah Lake Tower Branch',
        'ENBD - Dubai - Jebel Ali Branch',
        'ENBD - Dubai - Junction Mall Branch',
        'ENBD - Dubai - Jumeirah Village Circle Branch'
    ],
    'Sharjah & NE Region': [
        'ENBD - Ajman - Ajman City Center Branch',
        'ENBD - Ajman - Ajman Main Branch',
        'ENBD - Fujairah - Fujairah Main Branch',
        'ENBD - Ras Al Khaimah - Ras AL Khaimah Corniche Branch',
        'ENBD - Sharjah - Sharjah City Center Branch',
        'ENBD - Sharjah - Sahara Mall Branch',
        'ENBD - Sharjah - Matajer Al Quoz Branch',
        'ENBD - Sharjah - Sharjah Main Branch',
        'ENBD - Sharjah - Al Zahia City Centre Branch',
        'ENBD - Sharjah - Sharjah AlSuyouh Branch',
        'ENBD - Umm Al Quwain - Umm Al Quwain Branch'
    ]
}

region_to_branch_ei = {
    'Abu Dhabi & Al Ain Region': [
        'EI - Abu Dhabi - Khalifa City Branch',        
        'EI - Abu Dhabi - Abu Dhabi Mall Branch',
        'EI - Abu Dhabi - Bawabet Al Sharq Branch',
        'EI - Al Ain - Jimi Mall Branch',
        'EI - Abu Dhabi - Abu Dhabi Branch',
        'EI - Abu Dhabi - Main Branch Abu Dhabi',        
        'EI - Al Ain - Al Ain Branch'
    ],
    'Bur Dubai Region': [
        'EI - Dubai - Diyafa Road Branch',
        'EI - Dubai - Bur Dubai Branch',
        'EI - Dubai - Sheik Zayed Road Branch',
        'EI - Dubai - Healthcare City Branch',
        'EI - Dubai - Jumairah Road Branch',
        'EI - Dubai - Al Wasl Road Branch',
        'EI - Dubai - Al Barsha Mall Branch',
        'EI - Dubai - Dubai Mall Branch',
        'EI - Dubai - Al Barsha Heights Branch',
        'EI - Dubai - Dubai Hills Branch'
    ],
    'Deira Region': [
        'EI - Dubai - Dubai Festival City Branch',
        'EI - Dubai - Warqaa Mall Branch',
        'EI - Dubai - Al Mizher Branch',
        'EI - Dubai - Nad Al Hamar Branch',
        'EI - Dubai - Al Tawar Branch',
        'EI - Dubai - Nad El Shiba',
        'EI - Dubai - Baniyas Branch',
        'EI - Dubai - Dubai Land Dept Branch',
        'EI - Dubai - Khawaneej Walk Branch',
        'EI - Dubai - Silicon Central Mall Branch'
    ],
    'Sharjah & NE Region': [
        'EI - Sharjah - Halwan Branch',
        'EI - Sharjah - Al Rahmaniya Mall Branch', 
        'EI - Sharjah - Juriena Zero 6 Mall Branch',
        'EI - Sharjah - Qasimiyah Branch',
        'EI - Sharjah - Khorfakkan Branch',
        'EI - Ras Al Khaimah - Ras Al Khaimah Branch',
        'EI - Ajman - Ajman Kalifa Bin Zayed Branch',
        'EI - Fujairah - Fujairah Branch'
    ]
}

