name: Google Reviews Automation

on:
  schedule:
    - cron: '0 18 * * 5'

  workflow_dispatch:

jobs:
  run-script:

    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install XVFB
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

        run: |
          xvfb-run python daily.py